- name: "Install app node"
  hosts: aula
  become: yes
  gather_facts: yes
  vars:
    repo: "https://github.com/bgsouza/app_node2/archive/master.zip"
    path_app: /usr/app
    owner: root
    group: root
    mode: 0755
    app_name: app
  tasks:
    - name: "1. Create folder"
      file:
        path: "{{ path_app }}"
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    - name: "2. Install unzip"
      package:
        name: 
          - unzip
          - pm2
        state: latest
      register: install_packages

    - name: "3. Download and unzip app"
      unarchive:
        src: "{{ repo }}"
        dest: "{{ path_app }}"
        remote_src: yes
      register: download_file
      when: install_packages is success
    

    - name: "4. Compile app"
      npm:
        name: "{{ app_name }}"
        path: "{{ path_app }}"
      when: download_file is success

    # - name: "5. Install pm2 using npm"

    - name: "6. Run app"
      command: "pm2 start {{ path_app }}/{{ app_name }}/app.js"